---
# tasks file for aap.network_test

- name: Ping test
  ansible.builtin.ping:
  register: ping_result

- name: DNS lookup
  ansible.builtin.command: "nslookup {{ inventory_hostname }}"
  register: dns_result
  ignore_errors: yes

- name: Trace route
  ansible.builtin.command: "traceroute {{ inventory_hostname }}"
  register: traceroute_result
  ignore_errors: yes

- name: Display results
  ansible.builtin.debug:
    msg: |
      Ping test result: {{ ping_result.ping }}
      DNS lookup result: {{ dns_result.stdout }}
      Trace route result: {{ traceroute_result.stdout }}
